WI global settings style changes
SillyTavern/SillyTavern pull request #2207
Opened 2024-05-10 02:46 UTC by Wolfsblvt

Seems like quite a few people miss that the setting in the WI panel can actually be opened to show the global settings.
Suggested change to make it more obvious and rename it.
Suggestion taken from [here](https://discord.com/channels/1100685673633153084/1100685673633153087/1238269314981822467).

Looks like this now:

![image](https://github.com/SillyTavern/SillyTavern/assets/9962104/6fb0b443-5ffc-453d-a966-ede94b00d09e)
![image](https://github.com/SillyTavern/SillyTavern/assets/9962104/99356033-5434-4f7b-b49b-d2ca61ea32cb)

2024-05-10 20:11 UTC, Cohee1207 commented
"Global Activation Settings" and we have a deal.

2024-05-11 05:57 UTC, Wolfsblvt commented
If we never add any general/global WI settings there, only about activation, then yes. Right now they all fit. Only the sorting insertion strategy is kinda borderline not about "activation" in itself, but eh.

Why am I arguing semantics. The UI change is the important part so you can see more easily that this is a collapsed settings category.

Now I could even see naming the second one "World Configuration" instead of "World Settings". Opinion?

2024-05-11 08:30 UTC, Cohee1207 commented
The second header could be removed at all. It does not convey any useful information.

2024-05-11 08:32 UTC, Wolfsblvt commented
Well, it's the second header that now actually makes it look that the first one isn't just the header for the main content box below, but a **separate** header with its own content, just collapsed.

That's the whole issue, with people not noticing that this can be expanded.

2024-05-11 08:36 UTC, Cohee1207 commented
This has a simple yet elegant solution `class="standoutHeader"`
![image](https://github.com/SillyTavern/SillyTavern/assets/18619528/02fa149e-0012-4cd6-81b6-30d758c7a5b6)

2024-05-11 08:42 UTC, Wolfsblvt commented
Oh, the consistency. My heart...

Yes, I'd agree, this would work. But now look how the headers are in the one other place where we also have a collapsed-by-default header.
All the other headers are that standout, but that one isn't?
![image](https://github.com/SillyTavern/SillyTavern/assets/9962104/a2525c6d-222a-4bdc-95cc-c7c75d9a5e70)

Then it's much closer to the Advanced panel of the character editor. Which has "normal" headings like here, but there it works because the already expanded section has its own header.
![image](https://github.com/SillyTavern/SillyTavern/assets/9962104/fdae7536-95fc-498b-9ac7-84678605ebc2)

I don't know. There is no nice solution. But same as I didn't (and still don't) like the collapsed header int he settings page, I don't think this here in WI is a good design, if the section below does not have it's own header.
You don't really see what you collapse and expand.

I would call this nitpicking, but there were multiple people who didn't seem to get that this is a section you can actually open. That's why this PR exists :D

2024-05-11 08:43 UTC, Cohee1207 commented
Counter-argument: The extension panel has all collapsed drawers have this style.

2024-05-11 08:43 UTC, Cohee1207 commented
So the arrow should give the idea that this is clickable. Also a cursor.

2024-05-11 08:46 UTC, Wolfsblvt commented
Yes, but they each are visibly their own section, and the section below is visibly a new section not being part of the one above.

I mean, it can work. Better than what we have right now for sure. Would work even better if we had two rows of expandable settings like in the extensions panel, then it's even more obvious, so a good chance to add more WI settings, heh.

2024-05-11 10:07 UTC, Cohee1207 requested changes
TL;DR
1. Global Activation Settings moniker: 👍 
2. Visible drawer header: 👍 
3. Second header for the editor: 👎

2024-05-11 17:12 UTC, LenAnderson commented
Like wolf said, this is the same issue that exists with the user settings. Your throwing a drawer somewhere in the middle of non-drawer content and the visual distinction is not at all obvious. This is made worse by ST drawers having no separation at all between their content and other stuff around them. Drawer content just kinda exists below the header when expanded with no separation from other content.
While this is fine in the extension settings where everything is a drawer and one drawer's content ends where the next drawer header starts, here (and in user settings, where it is even worse because the drawer header looks very similar to section headers) that type of clear visual separation is just missing.
When collapsed, the drawer looks like a header for the content coming after it. When expanded, you can't tell where the drawer ends.
Having a header for the next block of content, even if that is not a collapsible drawer, makes it a lot clearer where one thing ends and the next begins.
And don't try and sell me the hr as a visual separation. That thing is styled so faint, it might just as well not be there at all.

2024-05-11 17:16 UTC, Cohee1207 commented
Even if the header is needed for better visualities, I'd prefer it being something like "World Editor" instead, cause "World Settings" lacks... settings.

2024-05-11 17:25 UTC, Cohee1207 commented
![image](https://github.com/SillyTavern/SillyTavern/assets/18619528/05bdf63b-6099-4985-9559-7b4dc380c334)
Here's a little idea: make drawer content "drown" in the surrounding background the same way inputs do (border + darker background).

2024-05-11 18:41 UTC, LenAnderson commented
That would help with one half of it. Even better if the content wasn't disconnected from the header.

2024-05-11 19:40 UTC, Cohee1207 commented
Done. What's the second part?

2024-05-11 19:41 UTC, LenAnderson commented
Making the collapsed drawer not look like a header for the loose content below it.

2024-05-11 19:42 UTC, Wolfsblvt commented
We circling back to my original intention.... ((:

2024-05-11 21:28 UTC, Cohee1207 requested changes
I give up on this, my UX vision is greatly impaired.
Just let me know when to merge.

2024-05-11 21:37 UTC, Wolfsblvt commented
Let's just postpone this until the other WI reworks.
We need to add more settings anyway with the new global stuff. I'll think about it again then.

2024-05-12 15:09 UTC, Cohee1207 commented
Feel free to reopen when you feel like it.

2024-05-12 15:09 UTC, closed without merging