Update zh-cn.json
SillyTavern/SillyTavern pull request #2411
Opened 2024-06-23 11:48 UTC by steve02081504

2024-06-23 12:03 UTC, Wolfsblvt commented
I feel like we should find a better way to get translatable strings for the buttons than manually adding them hidden to the already existing DOM.

If we go this way, there is no reason why we'd have to do custom buttons for popups really.

Also don't feel like adding translation properties to the actual code-behind classes that have to be provided with all the code calls of popups is a good choice either.

Don't have a good solution yet, but let me think about this.

2024-06-25 12:09 UTC, Cohee1207 commented
Please revert changes related to buttons. You can leave the rest (HTML attributes).

2024-06-25 13:15 UTC, steve02081504 commented
> Please revert changes related to buttons. You can leave the rest (HTML attributes).

fixed

2024-06-25 13:42 UTC, Wolfsblvt requested changes
Still visually breaks a few things that should be dealt with first, I figure.
@Cohee1207 see my review comments.

2024-06-25 13:42 UTC, Wolfsblvt commented on public/scripts/templates/charTagImport.html
> +<h3><span data-i18n="Import Tags For _begin">Import Tags For</span>{{charName}}<span data-i18n="Import Tags For _end"></span></h3>
This breaks layout for any space-reliant language.
![image](https://github.com/SillyTavern/SillyTavern/assets/9962104/8983ad3b-08da-48a9-b569-0789cb476c4a)

2024-06-25 13:42 UTC, Wolfsblvt commented on public/scripts/templates/charTagImport.html
> +            <span data-i18n="Remember my choice">Remember my choice</span>
Closing the span before the fa icon isn't what is usually used in ST.  
Breaks the formatting of the icon inline a bit at least, making weird alignment.  
Below is this PR, top is on staging.
![image](https://github.com/SillyTavern/SillyTavern/assets/9962104/1e93b856-677d-41b9-90c3-e792b3ab7c55)

2024-06-25 13:42 UTC, Wolfsblvt commented on public/scripts/popup.js
> +        if (okButton) {
This `if` prevents the fault text of `OK` from being inserted into the button by default, if not defined by the function call.  
Don't ask me why it's "Cancel" in the HTML, and default to "OK" in the js code, but we shouldn't break it, or many popups would look wrong.

2024-06-25 13:42 UTC, Wolfsblvt commented on public/scripts/popup.js
> + * @property {string} text_i18n - The i18n key of the button
Forcing a translation property onto every button a dev might design is not a good design. At least imho. Either use the actual button text as a translation base value, or there would actually have to be some kind of selector functionality to "find" the contents to translate.

With code changes like this, you blow up actual development code and contributor stuff with needed translation values.

Generally, I think translation is a reasonable thing. But it should be an *afterthought*, coming after the actual devving of features. If it's breaking code, or making coding more complicated, its a kind of trade-off that I am not sure is worth it. Personally.

2024-06-25 13:42 UTC, Wolfsblvt commented on public/scripts/templates/charTagImport.html
> +            <span data-i18n="Remember my choice">Remember my choice</span>
Still an issue. Small one though. I think you can just revert to the older, big <span> tag again and add a small one just for the text with your il18n attribute.

2024-06-25 13:42 UTC, Wolfsblvt commented on public/scripts/templates/charTagImport.html
> +<h3><span data-i18n="Import Tags For _begin">Import Tags For</span>{{charName}}<span data-i18n="Import Tags For _end"></span></h3>
Also still here. You *might* be able to solve this by making the text heading a flexbox and then using `justify-content: space-between;`, but I am not sure.

2024-06-25 13:55 UTC, Cohee1207 commented on public/scripts/templates/charTagImport.html
> +<h3><span data-i18n="Import Tags For _begin">Import Tags For</span>{{charName}}<span data-i18n="Import Tags For _end"></span></h3>
Or `&nbsp;` before the macro. Adds a space for every language, but it's a lesser evil.

2024-06-25 14:00 UTC, steve02081504 commented on public/scripts/templates/charTagImport.html
> +<h3><span data-i18n="Import Tags For _begin">Import Tags For</span>{{charName}}<span data-i18n="Import Tags For _end"></span></h3>
Some languages may not want this space to exist so
Fixed.

2024-06-25 14:04 UTC, Wolfsblvt commented on public/scripts/templates/charTagImport.html
> +<h3><span data-i18n="Import Tags For _begin">Import Tags For</span>{{charName}}<span data-i18n="Import Tags For _end"></span></h3>
That's actually clever. That works.

2024-06-25 14:10 UTC, steve02081504 commented on public/scripts/templates/charTagImport.html
> +            <span data-i18n="Remember my choice">Remember my choice</span>
may fixed in [`8117d9a` (#2411)](https://github.com/SillyTavern/SillyTavern/pull/2411/commits/8117d9aafd285a6d3219606f7865dfbd114efefa) ..?

2024-06-25 14:12 UTC, steve02081504 commented on public/scripts/popup.js
> +        if (okButton) {
I'm not sure why I'm seeing this review two days later...
Sorry if it put you in a bad mood.😢

2024-06-25 14:13 UTC, steve02081504 commented on public/scripts/popup.js
> + * @property {string} text_i18n - The i18n key of the button
as above, I'm not sure why I'm seeing this review two days later...
Sorry if it put you in a bad mood, again.😢

2024-06-25 14:14 UTC, Wolfsblvt commented on public/scripts/popup.js
> +        if (okButton) {
All good! You didn't, it's oki.

2024-06-25 14:16 UTC, Wolfsblvt approved these changes
All good now.

2024-06-25 14:51 UTC, merged