Add bulk tag import
SillyTavern/SillyTavern pull request #2663
Opened 2024-08-15 15:15 UTC by d-ber

This PR adds two buttons to allow bulk tag import.  They are located in the "Tag" menu in bulk edit mode. 
One is used to import all tags, while the other is used to import existing tags only, similarly to the "Import Tags" menu for a single character. 
The following picture shows the modified menu.

![Screenshot_new_buttons](https://github.com/user-attachments/assets/b09ad771-7463-44e4-8ca1-8f630afc40a4)

## Checklist:

- [x] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

2024-08-15 15:17 UTC, Cohee1207 commented on public/scripts/tags.js
> +        : importAll ? tag_import_setting.ALL
Please consider rewriting to something more straightforward as three ternaries on one line is not very readable.

2024-08-16 10:41 UTC, Wolfsblvt requested changes
Small things I'd say should be changed. Besides that, good idea.

I'd rather prefer to port over the whole bulk edit to the new popup, which would solve a few of the display issues you encountered anyway by default, but I don't wanna push that task onto you.

2024-08-16 10:41 UTC, Wolfsblvt commented on public/style.css
> +    width: 750px;
Even if this *only* applies to the old legacy popups, we shouldn't just change the base width like this. This applies to all popups using that.
We have the `wider_dialogue_popup` CSS class applied for popups that should be wider. That one is used for the "Import Tags" popup too, for example.

Some of these days we should for sure update the bulk edit popups to the new popup functionality. Until then, could you check if we can find a way to just add the CSS class to the shadow popup for this?

I don't want to change the base width.

2024-08-16 10:41 UTC, Wolfsblvt commented on public/scripts/BulkEditOverlay.js
> +    }
If you update/change the tags for characters, you need to reprint the character list in the background. That one will not refresh automatically. Check how the other functions are doing it, like reset or removing mutual.
Should simply be calling `printCharactersDebounced();`.

Goes for this and the `importAllTags` too.

2024-08-16 10:41 UTC, Wolfsblvt commented on public/scripts/tags.js
> +    }
That's a bit repetitive. How about we change it and don't supply three different boolean switches, but an actual `manualImportSettingsOverride` or whatever, that is default null. But can also be all of the other options.

That also covers the `forceShow` case by simply supplying `tag_import_setting.ASK` there.

Slims down the optional args for both those functions, and is what you actually wanna do anyway.

2024-08-16 20:23 UTC, d-ber commented on public/scripts/BulkEditOverlay.js
> +    }
Thank you for the review. I found out that `printCharactersDebounced()` is called within `addTagsToEntity()`, which is used to import tags inside `importTags()`. The character list is refreshed when using these functions as they are.

2024-08-17 21:10 UTC, Wolfsblvt approved these changes
Looks good now. Thanks for the changes!

Tested a few things, and seems to work as intended.

@Cohee1207 you wanna test/merge?

2024-08-17 21:34 UTC, Cohee1207 approved these changes
Seems to be working as expected.

2024-08-17 21:34 UTC, merged