Implement Connection Manager
SillyTavern/SillyTavern pull request #2797
Opened 2024-09-06 21:53 UTC by Cohee1207

It's a wrapper for STscript commands with a fancy interface. The idea is _not_ stolen TalOS-Reborn, all coincidences are coincidental.

> [!IMPORTANT] 
> IT IS NOT PRESET PRESETS!

<img width="500" alt="image" src="https://github.com/user-attachments/assets/67a2cb34-529d-4357-a72f-80837798d14c">

## Checklist:

- [X] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

2024-09-06 23:55 UTC, RossAscends reviewed
1. i would like to see this as core code, not an extension.
2. if tokenizer is being added into the profile attributes, the selector should be moved in here too (which would only be possible/sane if it's core code)

2024-09-07 00:26 UTC, Wolfsblvt commented
1. Can be a core extension enabled by default. We have a few of those. Even QR, is not ***really*** core, if you think about it. Think this is a reasonable approach. Especially CC people likely won't care about this at all.
2. Advanced Formatting and Instruct is also not part of this tab, for the API. still part of the profile. Context too. All TC things actually. Why is the Tokenizer special to be moved?

2024-09-07 12:02 UTC, Cohee1207 commented
1. I think at this point adding new core features is always a tough decision, because of xkcd 1172 (see below). So I'd want to give an ability to disable this for those who don't need it.
2. I don't think the API pane is a proper place for the tokenizer since you can switch between Together/Mancer/OpenRouter/local and would still have the same Llama 3 model running under the hood with the same tokenizer and formatting. In the ideal world, API endpoints would provide the methods of tokenization and we would not have to worry about tokens anymore. By we're not in the ideal world.

![xkcd 1172](https://imgs.xkcd.com/comics/workflow.png)

2024-09-07 17:43 UTC, Wolfsblvt requested changes
#### 1. Consistent Font Awesome Icons
![image](https://github.com/user-attachments/assets/9d162b7c-1405-4541-9ffd-13dab1f2a8e5)

I know I am being nitpicky here. But I'd like to see consistent icon style.
"Reload" can be debated if it's the same as "Restore", but it functions very similar, so I'd say yes.
"Delete" can simply be the same trash can.
"Save as.." mas sense with the icon we use in other places, it's not really "New", as there is no actual new content created.

#### 2. Enforce Unique Names
The unique name gen thingy is good. (Though we now have the third functionality that does unique name building in a third, different way)
But you should enforce names by checking on existing profiles on save too. For both slash command and the button itself. Likely inside the save function?
It's easily overridable by just typing the same name manually, which will screw with most of your logic, going by unique names.

![image](https://github.com/user-attachments/assets/598bdedc-86db-4d32-919a-54960d0e423c)

#### 3. Console Exception for Main API on Load/Refresh
Happens regularly. Even when switching between profiles.
The rest of the profile is still loaded correctly. I think you are also not passing errors correctly along to the profile selector itself. Dunno if you **want** to continue executing on errors.
Correction, also happens when switching to a CC profile.

![image](https://github.com/user-attachments/assets/e39c9b8b-cc57-4c93-94b6-33bfadf87c5c)
![image](https://github.com/user-attachments/assets/3e4382b0-9b4a-45a7-a55f-a68fbaa3ba54)

#### 4. Long Execution, Indicator Needed
Especially with TC it seems like the commands might take a while to execute all of them, command by command.
There is no visual indication if they still run. Especially because you switch main api first, which is on the same panel, it looks like it might already be done, while the commands are still running.
I accidently switched to the AF panel and changed the context preset during testing **before** it was changed with this command.
Should add at least a visual indicator. I would even say block the UI. Similar to the QR execution in the QR editor, make a blocking transparent popup or something, that prevents **all** inputs until it is done.

Same btw for running the slash commands. They don't have a "finished" toast either.
You should likely just add a success toast at the end of switching/loading anyway. In addition to the blocking behavior explained above. The "Refresh" functionality already has a toast at the end.

#### 5. Context Templates Still Toast
![image](https://github.com/user-attachments/assets/81d08759-ab12-4338-acb8-7ab69acad95d)

I checked, there is no quiet flag in there yet. That's likely the reason. Also, that toast is ages old. "Auto-select" is the wrong wording anyway, as the same function is used everywhere to just *select* the template, not just for auto-select.

#### 6. What Happens On Manual Change
Maybe a bit of an opinionated point, not really a bug/issue. But if you already have the "<None>" option, wouldn't it make more sense that switching any of the things inside a profile manually (api, templates, tokenizer, etc) will set the profile to NONE, as you currently don't really have a profile selected anymore? You manually modified your stuff.
I can see that this would be an issue with changing and overwriting a profile though.
Maybe leaving it as is is good enough.
People were already asking for "dirty" indicators on the templates/sampler settings too. Maybe this is something to be done for all of those at once.

#### Additional Stuff / Questions
1. If someone deletes a sampler preset or instruct/context, the profile will not notice this. Should be fine - I mean kinda your fault. At least you still get a toast.
2. Would be nice if the `/profile` slash command hat an `await` argument too, to be blocking until the profile is loaded.

2024-09-07 17:43 UTC, Wolfsblvt commented on public/scripts/slash-commands.js
> +    options.escapeHtml = args.escapeHtml !== undefined ? isTrueBoolean(args.escapeHtml) : true;
This is not needed, we have set `escapeHtml` set to default globally. But I don't object, it doesn't change anything.

2024-09-07 17:43 UTC, Wolfsblvt commented on public/scripts/extensions/connection-manager/index.js
> +        },
You still need to return empty string on callbacks. Good practice, and such.
Or return something meaningful, like the profile name. We do that on a lot of slash commands even on set.

2024-09-07 17:43 UTC, Wolfsblvt commented on public/scripts/extensions/connection-manager/index.js
> +                return '';
No warning if a save fails? That's kind of data loss. I'd expect at *least* a console log here, if not a toast.

2024-09-07 17:43 UTC, Wolfsblvt commented on public/scripts/extensions/connection-manager/index.js
> +            console.log(`Profile not found: ${profileId}`);
You'll run into this log if you select the "&lt;None&gt;" option in the dropdown. Doesn't hurt, but it's a bit wrong. Should likely add specific logif for that NONE profile here.

2024-09-07 17:43 UTC, Wolfsblvt commented on public/scripts/extensions/connection-manager/index.js
> +    ...extension_settings.connectionManager.profiles.map(p => new SlashCommandEnumValue(p.name, p.name, enumTypes.name, enumIcons.server)),
No need to make this multiline if the name and display name are the same value. You can just set the second argument to `null`, looks cleaner.

2024-09-07 18:36 UTC, Cohee1207 commented on public/scripts/slash-commands.js
> +    options.escapeHtml = args.escapeHtml !== undefined ? isTrueBoolean(args.escapeHtml) : true;
It wasn't working for whatever reason in staging. Pretty strange that now it does. But it's good to have it here explicitly set to true.

2024-09-07 23:19 UTC, Wolfsblvt approved these changes
Two last small nitpicks that I fixed.
Is only marginally related to this, but I mentioned it here in the branch, and you changed/used the quiet flags anyway, so I added this here.
Second one is disabling the buttons that you can't use, because... duh.

Tested the PR one last time and couldn't find anything else.
Looks very nice.

People will be so so happy.
(I'll tell anyone those are not preset-presets, I promise.)

2024-09-07 23:56 UTC, merged