Markdown hotkeys for textareas
SillyTavern/SillyTavern pull request #2800
Opened 2024-09-07 01:09 UTC by RossAscends

adds hotkeys to insert markdown formatting characters in textareas: 

`ctrl+b` for bold
`ctrl+i` for italics
`ctrl+u` for underlined text
`ctrl+backspace` for strikethrough

considerations: 
- may need to be debounced?
- it hijacks the ctrl+u keybind (open page source on chrome)

2024-09-07 07:56 UTC, RossAscends commented
It's come to my attention that `ctrl+backspace` is a OS-level hotkey used to delete whole words. open to suggestions for alternatives.

2024-09-07 12:08 UTC, Cohee1207 commented
`Ctrl+Tilde`

2024-09-07 12:09 UTC, Cohee1207 commented on public/scripts/input-md-formatting.js
> +    $('textarea').on('keydown', function (e) {
I'd like to limit it to only input textarea and (possibly) character editors.

2024-09-07 14:02 UTC, LenAnderson commented
> `Ctrl+Tilde`

If you opt to use special character keys, you might want to use the event's `.code` property instead of `.key` to make them work on non-English keyboard layouts. And display the localized key combo somewhere (if the browser supports that, no Firefox, I think).


And just repeating this here for visibility: 
don't apply the formatting by setting a new value on the textarea, that breaks native undo/redo

2024-09-07 14:04 UTC, LenAnderson commented on public/scripts/input-md-formatting.js
> +    $('textarea').on('keydown', function (e) {
Why not give the inputs an attribute or class to "subscribe" to the hotkey features.

2024-09-07 16:31 UTC, Wolfsblvt commented on public/scripts/input-md-formatting.js
> +    $('textarea').on('keydown', function (e) {
+1 for that suggestion. Like the `interactable` class. Using classes to define intention makes it much easier to be used in extensions, when adding new controls, etc.

2024-09-07 20:34 UTC, Wolfsblvt reviewed
Besides the Ctrl+Backspace being reserved (which I personally use a lot) which was already mentioned,
Ctrl+U is also used in many browsers. Opens the sources.

Question is, do we **need** hotkeys for this? Many other pages don't have it either. GitHub for example, where we are on right now, [only has one for italic and bold](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#styling-text).

Some more feedback:

1. As Len said, this should both not break CTRL+Z on the input itself, and should in itself be CTRL+Z-able too.
2. I'd love it to work more like the formatting used in other places. So doing the same formatting on an already formatted string removes it. Instead of adding it two, three four times.
  Try how it works here on GitHub. A bit more intuitive.
  It's likely just checking the chars before and after the current selection/cursor too.
3. Would also be nice if the actual formatting happens on a ***trimmed*** part of the string. So spaces at the start or end don't get formatted with it.
  Because when you use double-click to select a word for example, it usually selects the space at the end too.
Here again, check how GitHub does it.


The general idea is very cool and this would be useful. Just needs a bit more tuning.

2024-09-07 21:36 UTC, RossAscends commented
@LenAnderson ok added the subscribe-able class instead of blanket application. regarding Undo, I understand the concern and can confirm it does back Ctrl+Z undo. However i'm unsure how to programmatically edit the input's value (which breaks ubndo)...without programmatically editing the input's value. Suggestion?

@Wolfsblvt added reversibility to the hotkey. If the MD formatting already exists, it gets removed instead. also fixed the trailing space issue.

I took @Cohee1207 's suggestion about ctrl+tilde (effectively `ctrl+shift+backquote`) for strikethrough.

I also would like to use `ctrl+backquote` to add single backticks for inline code, but this is used in Chrome for 'swap to previous tab'. Not sure if this is another beloved-yet-obscure hotkey. Opinions?

2024-09-07 21:41 UTC, LenAnderson commented
> @LenAnderson ok added the subscribe-able class instead of blanket application. regarding Undo, I understand the concern and can confirm it does break Ctrl+Z undo. However i'm unsure how to programmatically edit the input's value (which breaks undo)...without programmatically editing the input's value. Suggestion?

`document.execCommand()` can be used for that. Have a look at the QR editor (`QuickReply.js:650`) for implementation. That file also has an example for showing the user what the key-combo is on *their* keyboard layout (`QuickReply.js:620`).

2024-09-07 22:16 UTC, RossAscends commented
@LenAnderson I saw the .execCommand() was depreciated and went looking for a different solution. landed on `.setRangeText()`

It gives some undo compatibility, but in my testing it restarts the Undo history at the point of the most recent hotkey. So if you do multiple hotkeys in the same text area, you lose the history that came before the most recent one. Not perfect, but better than completely wiping it. Think this can be improved?

2024-09-07 22:32 UTC, LenAnderson commented
Does not just disable, but break undo/redo entirely in Chrome. Adds some gibberish mix of old and new text on ctrl+z.

1. Select bar and ctrl+b  
![broken-01](https://github.com/user-attachments/assets/6a01520d-6503-4d62-ae15-ec196ea55435)
1. Asterisks get added  
![broken-02](https://github.com/user-attachments/assets/6f2ba3e1-2623-4042-b195-7a94d4bc869c)
1. ctrl+z: no undo but cursor jumps to start  
![broken-03](https://github.com/user-attachments/assets/234b372c-a8c2-4889-a2f3-8d0e82797577)
1. ctrl+y: weird shit gets added  
![broken-04](https://github.com/user-attachments/assets/27e5a593-c869-406d-bc45-72d9ed0bb4a0)


Just use execCommand. That properly retains history and I don't see it going away anytime soon. If it does, it's not going to go without a fuss so there'll be plenty of notice to switch to a lesser solution then.

Also just noticed while testing undo, when pressing one of the hotkeys without a selected range, just the caret in a word or at a word boundary, that whole word should get the formatting.

(pipe is caret):
`foo|bar` -> `ctrl+b` -> `**foobar**`
`foobar|` -> `ctrl+b` -> `**foobar**`

Currently it just adds `****` wherever the cursor is.

2024-09-07 22:57 UTC, RossAscends commented
switched over to execCommand. 

As for the "any word touching the caret should get the formatting, even if it's not a selection" suggestion: I'm not sure how I feel about that. I've never experienced any text editor behaving that way.

2024-09-07 23:08 UTC, Cohee1207 commented
> As for the "any word touching the caret should get the formatting, even if it's not a selection" suggestion: I'm not sure how I feel about that. I've never experienced any text editor behaving that way.

You likely just never noticed. GitHub does that. But not Discord. And not MS Word.

2024-09-07 23:14 UTC, RossAscends commented
huh ok. however there is a quirk in github where "if caret is at the end of the full text (with not even a space after it), then even if the caret is touching a word's end, it won't format the word, and instead inserts the format wrapper at the caret". 

Either way I think I'd prefer to force selection, or at least ignore cases of 'caret at start/end of word'. 'caret in the middle of a word' is easier to detect.

2024-09-07 23:24 UTC, LenAnderson commented
MS Word does not do edge toggle but does in-word toggle. That at the very least should be implemented.

2024-09-07 23:29 UTC, Wolfsblvt commented
Yeah, even GitHub is a bit inconsistent, or outright buggy with this, I just noticed.
This one doesn't make sense at all.
![git_format](https://github.com/user-attachments/assets/41321db9-5bfa-49ee-bd91-008720158f5d)

My opinion:
If you are inside a word, so not at any word boundary position, format the word you are inside (word boundary check).
If you are at the edge, at the end/start, etc. So anywhere where there is a word boundary, just toggle insertion of the format characters and put the cursor inside.

2024-09-10 19:55 UTC, Cohee1207 requested changes
Inline Kode hotkey nukes what's currently selected. Pressing Ctrl+Z once returns it to normal.

2024-09-11 04:41 UTC, RossAscends commented
@Cohee1207 I can't reproduce. Can you be more specific? 

Tested: 
1. type 'test' into input bar. 
2. select the word.
3. hit Ctrl+K
4. test gets wrapped in backticks. 
5. leaving the selection as is, hit Ctrl+K again.
6. backticks are removed as expected.

2024-09-11 04:58 UTC, RossAscends commented
regarding 11989ea: I wasn't aware cohee had already added it. his is fine, so i remerged and reverted my hotkey help text

2024-09-13 17:59 UTC, cloak1505 commented
`Ctrl + Shift + u` or `Ctrl + Shift + _` for underline, or did you guys come up with something else?

2024-09-13 20:06 UTC, Cohee1207 commented
Is there anything wrong with Ctrl+U? I don't think "open page source" (is that still a thing?) is a valuable keybind to be used when focused in a text input.

2024-09-13 20:41 UTC, cloak1505 commented
Ignore my comment. sorry. I missed that you can hijack the hotkey so it *won't* open Page Source.

2024-09-14 11:16 UTC, Cohee1207 approved these changes

2024-09-14 11:16 UTC, merged