Add german readme
SillyTavern/SillyTavern pull request #2914
Opened 2024-09-28 13:31 UTC by X00LA

## Checklist:

- [X] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

2024-09-28 21:42 UTC, Wolfsblvt requested changes
Stopped at the "Installation" section. This is taking too much of my time.

Did you use machine translation for this without manually vetting and fixing all the issues and mis-translations and made sure that actual technical wording that made sense stays english?

If I continue going through this, I might've been faster to translate this with ChatGPT and manually fixing myself.

I am sorry, but I think the quality is not much better than what browser-internal translation tools provide out of the box.

Can you update this PR to actual reasonable translations? Otherwise I'd think we can just close this and let Germans read the actual english readme.

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +SillyTavern bietet eine einheitliche Benutzeroberfläche für viele LLM-APIs (KoboldAI/CPP, Horde, NovelAI, Ooba, Tabby, OpenAI, OpenRouter, Claude, Mistral und mehr), ein mobilfreundliches Layout, ein
Not sure if it's a good idea to translate "Extensions", with how much that word is tied to functionality and documentation in ST. Though of course, I know the *wish* to translate as much as possible.

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +SillyTavern (oder ST für kurz) ist eine lokal installierte Benutzeroberfläche, die es dir ermöglicht, mit Textgenerations-LLMs, Bildgenerierungsmaschinen und TTS-Sprachmodellen zu interagieren.
```suggestion
SillyTavern (oder ST abgekürtz) ist eine lokal installierte Benutzeroberfläche, die es dir ermöglicht, mit Textgenerations-LLMs, Bildgenerierungsmaschinen und TTS-Sprachmodellen zu interagieren.
```

Also, what are "Bildergenerierungsmaschinen"? :D

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +1. Wir möchten die Nutzer mit so viel Nutzen und Kontrolle über ihre LLM-Eingabeaufforderungen wie möglich ausstatten. Die steile Lernkurve ist Teil des Spaßes!
"LLM-Eingabeaufforderungen" sounds very weird. Might be a better way to translate that, if it has to be translated. Likely "Anweisungen". "Instruktionen" might be too much leaning into actual instruct templates.
But honestly, most German sites I've read so far do not translate too much of the LLM lingo. So it should just stay "Prompt".
```suggestion
1. Wir möchten die Nutzer mit so viel Nutzen und Kontrolle über ihre LLM-Prompts wie möglich ausstatten. Die steile Lernkurve ist Teil des Spaßes!
```

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +2. Wir bieten keine Online- oder gehosteten Dienste an, noch verfolgen wir programmgesteuert Benutzerdaten.
```suggestion
2. Wir bieten weder Online- oder gehosteten Dienste an, noch verfolgen wir programmgesteuert Benutzerdaten.
```
fix grammar

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +## Zweige
```suggestion
## Branches
```
Even the german GitHub doc does not translate the word "Branches".

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +SillyTavern wird mit einem Zweigsystem entwickelt, um ein reibungsloses Erlebnis für alle Nutzer zu gewährleisten.
```suggestion
SillyTavern wird mit einem Zwei-Branches-System entwickelt, um ein reibungsloses Erlebnis für alle Nutzer zu gewährleisten.
```

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +* `release` -🌟 **Empfohlen für die meisten Nutzer.** Dies ist der stabilste und empfohlene Zweig, der nur aktualisiert wird, wenn wichtige Versionen veröffentlicht werden. Er ist für die Mehrheit der
```suggestion
* `release` -🌟 **Empfohlen für die meisten Nutzer.** Dies ist der stabilste und empfohlene Branch, der nur aktualisiert wird, wenn größere Versionen und Änderungen veröffentlicht werden. Er ist für die Mehrheit der Nutzer geeignet. Typischerweise einmal im Monat aktualisiert.
```

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +* `staging` - ⚠️ **Nicht für den gelegentlichen Gebrauch empfohlen.** Dieser Zweig enthält die neuesten Funktionen, kann jedoch jederzeit instabil sein. Nur für Power-User und Enthusiasten. Mehrmals
```suggestion
* `staging` - ⚠️ **Nicht für den Gelegenheitsgebrauch order unerfahrenen User empfohlen.** Dieser Branch enthält die neuesten Funktionen, kann jedoch jederzeit instabil sein. Nur für Power-User und Enthusiasten. Mehrmals täglich aktualisiert.
```

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +Wenn du nicht vertraut mit der Verwendung der git CLI bist oder nicht verstehst, was ein Zweig ist, mach dir keine Sorgen! Der Release-Zweig ist immer die bevorzugte Option für dich.
```suggestion
Wenn du nicht vertraut mit der Verwendung der git CLI bist oder nicht verstehst, was ein Branch ist, mach dir keine Sorgen! Der Release-Branch ist immer die bevorzugte Option für dich.
```

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +### Vorgeschlagene Backends (nicht verbunden)
lol
```suggestion
### Vorgeschlagene Backends (keine Partnerschaft oder Werbebeziehung)
```

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +* [tabbyAPI](https://github.com/theroyallab/tabbyAPI) - eine beliebte, leichtgewichtige, lokal gehostete exl2 Inferenz-API
```suggestion
* [tabbyAPI](https://github.com/theroyallab/tabbyAPI) - eine beliebte, portable, speicherplatzoptimierte und lokal gehostete exl2 Inferenz-API
```

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +| [![][discord-shield-badge]][discord-link] | [Tritt unserer Discord-Community bei!](https://discord.gg/sillytavern) Erhalte Unterstützung, teile deine Lieblingscharaktere und Eingabeaufforderungen.
```suggestion
| [![][discord-shield-badge]][discord-link] | [Tritt unserer Discord-Community bei!](https://discord.gg/sillytavern) Erhalte Unterstützung, teile deine Lieblingscharaktere und Prompts. |
```

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +* [Erstelle ein GitHub-Problem](https://github.com/SillyTavern/SillyTavern/issues)
```suggestion
* [Erstelle ein GitHub-Issue](https://github.com/SillyTavern/SillyTavern/issues)
```
Same here. Cross-check GitHubs German docs, if you want to know the wordings they use. I would not deviate from those. They still use "Issue".

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +### Ich mag dein Projekt! Wie kann ich beitragen?
```suggestion
### Ich mag dieses Projekt! Wie kann ich beitragen?
```
Neither singular no plural is really accurate. Circumventing the use is the easiest solution.

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +2. Sende Funktionser Vorschläge und Problemmeldungen unter Verwendung der bereitgestellten Vorlagen.
```suggestion
2. Sende Feature Requests und Issues unter Verwendung der bereitgestellten Vorlagen.
```

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +3. Lies diese gesamte README-Datei und überprüfe zuerst die Dokumentationswebsite, um doppelte Probleme zu vermeiden.
```suggestion
3. Lies diese gesamte README-Datei und überprüfe zuerst die Dokumentationswebsite, um doppelte Issues zu vermeiden.
```

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +SillyTavern basiert auf dem Konzept der "Charakterkarten". Eine Charakterkarte ist eine Sammlung von Eingabeaufforderungen, die das Verhalten des LLM festlegen und erforderlich sind, um anhaltende Ge
```suggestion
SillyTavern basiert auf dem Konzept der "Charakterkarten". Eine Charakterkarte ist eine Sammlung von Prompts, die das Verhalten des LLM festlegen und erforderlich sind, um persistente Gespräche in SillyTavern zu führen. Sie funktionieren ähnlich wie ChatGPT's GPTs oder Poe's Bots. Der Inhalt einer Charakterkarte kann alles sein: ein abstraktes Szenario, ein Assistent, der für eine bestimmte Aufgabe maßgeschneidert ist, eine berühmte Persönlichkeit oder ein fiktiver Charakter.
```

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +Das Namensfeld ist der einzige erforderliche Eingabewert für die Charakterkarte. Um ein neutrales Gespräch mit dem Sprachmodell zu beginnen, erstelle eine neue Karte, die einfach "Assistent" genannt
```suggestion
Das Namensfeld ist der einzige erforderliche Eingabewert für die Charakterkarte. Um ein neutrales Gespräch mit dem LLM zu beginnen, erstelle eine neue Karte, die einfach "Assistent" genannt wird, und lasse die restlichen Felder leer. Für einen thematischeren Chat kannst du dem LLM verschiedene Hintergrundinformationen, Verhaltensweisen und Schreibmuster sowie ein Szenario geben, um das Gespräch zu beginnen.
```

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +Um ein schnelles Gespräch zu führen, ohne eine Charakterkarte auszuwählen, oder um einfach die LLM-Verbindung zu testen, gib einfach deine Eingabeaufforderung in die Eingabezeile auf dem Willkommensb
```suggestion
Um ein schnelles Gespräch zu führen, ohne eine Charakterkarte auszuwählen, oder um einfach die LLM-Verbindung zu testen, gib einfach dein Prompt in die Eingabezeile auf dem Willkommensbildschirm ein, nachdem du SillyTavern geöffnet hast. Bitte beachte, dass solche Chats vorübergehend sind und nicht gespeichert werden.
```

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +Um eine allgemeine Vorstellung davon zu bekommen, wie man Charakterkarten definiert, sieh dir die Standardfigur (Seraphina) an oder lade ausgewählte von der Community erstellte Karten im Menü "Erweit
```suggestion
Um eine allgemeine Vorstellung davon zu bekommen, wie man Charakterkarten definiert, sieh dir die mitgelieferte Charakterkarte (Seraphina) an oder lade ausgewählte von der Community erstellte Karten im Menü "Erweiterungen & Assets herunterladen" herunter.
```

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +## Hauptmerkmale
```suggestion
## Wichtigste Features
```
I don't think most places actually translate "Features". *Merkmale* is not the correct wording for sure.

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +* Erweiterte Texteinstellungen mit vielen von der Community erstellten Voreinstellungen
```suggestion
* Erweiterte Text-Generierungs-Einstellungen mit vielen von der Community erstellten mitgelieferten Einstellungen (Presets)
```

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +* Unterstützung für World Info: erstelle reichhaltige Lore oder speichere Tokens auf deiner Charakterkarte
This translation is just wrong.
```suggestion
* Unterstützung für World Info: Erstelle reichhaltige Lore oder reduziere die Tokens in deiner Charakterkarte
```

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +* Reichhaltige UI-Anpassungsoptionen: Themenfarben, Hintergrundbilder, benutzerdefiniertes CSS und mehr
I think Themes should not be translated either.
```suggestion
* Reichhaltige UI-Anpassungsoptionen: Themes zur Farbenwahl, Hintergrundbilder, benutzerdefiniertes CSS und mehr
```

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +* Umfangreiches Chat-Befehlsunterstützungssystem und eigene [Scripting-Engine](https://docs.sillytavern.app/usage/st-script/)
```suggestion
* Umfangreiches "Chat-Befehle"-System und eigene [Scripting-Engine](https://docs.sillytavern.app/usage/st-script/)
```

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +SillyTavern hat Unterstützung für Erweiterungen.
```suggestion
SillyTavern unterstützt Erweiterungen.
```

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +Tutorials zur Nutzung findest du in den [Docs](https://docs.sillytavern.app/).
```suggestion
Tutorials zur Nutzung findest du in der [Dokumentation](https://docs.sillytavern.app/).
```

2024-09-28 21:42 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +> * INSTALLIERE NICHT IN EINEM VON WINDOWS GESTEUERTEN ORDNER (Programme, System32 usw.).
```suggestion
> * INSTALLIERE NICHT IN EINEM VON WINDOWS KONTROLLIERTEN ORDNER (Programme, System32 usw.).
```

2024-09-29 05:42 UTC, X00LA commented on .github/readme-de_de.md
> +SillyTavern bietet eine einheitliche Benutzeroberfläche für viele LLM-APIs (KoboldAI/CPP, Horde, NovelAI, Ooba, Tabby, OpenAI, OpenRouter, Claude, Mistral und mehr), ein mobilfreundliches Layout, ein
I don't know what the problem is? The other translations are also ***complete*** translations, so ***why*** should be german any ***different***?

2024-09-29 06:18 UTC, X00LA commented
Checking the file for any spelling issues today!
I'll let you know as soon as it's done.

2024-09-29 12:32 UTC, X00LA commented
Fixed all issues and now it is a 1:1 tanslation from the original.
Fixed spelling issues and wrong text blocks.

2024-09-29 12:56 UTC, X00LA commented
Now everything should be correct.
I hope it satisfies your requirements?

2024-10-04 08:47 UTC, Cohee1207 commented
@Wolfsblvt are we good here?

2024-10-04 08:54 UTC, Wolfsblvt commented
Well, just from a quick glance I still saw like a handful mentions of „Zweig“, which is the German word for tree branch.

I mean, merge it if you want. I wouldn‘t consider this a good translation for a tech tool though.

2024-10-04 10:21 UTC, X00LA commented
I overlooked this "Zweig" (6 in one Paragraph that I overlooked) when proofreading and have now changed it. And "Zweig" does NOT just mean tree branch in German! It has, like in English, several meanings! Wolfsblvt is harping on about trivialities here.
Otherwise, this translation is a 1 to 1 translation.
I don't understand what there is to complain about?!
"I wouldn't consider this a good translation for a tech tool though." So "Wolfsblvt" then the original is probably not good enough either?
Send my translation through a translation tool of your choice and you should get an almost identical English version!
But if it's not good enough, then I have no problem with it not being used and instead Wolfsblvt creating one to meet her requirements.

2024-10-04 10:41 UTC, Wolfsblvt commented
Well, "Zweig" might be uses in context like ancestry trees or branching roads. Sure. Still not the word most common sites and tools use to translate "branches".

That's what I meant with *decent translation for a tech tool. Your translation is good - besides a few issues that you mostly fixed.  
It translates IT and tech terms into German that many people in that area would not translate though. That was my first big complain here.

I am biased though. Even as a native German speaker, I don't like reading anything tech in German. Makes me cringe.  
I can still see the use for people being less fluent in reading English, so a German readme for sure is a good idea. It's just that we can likely debate for weeks which words should not be translated, because people should have the most basic knowledge in English terms that are setting the precedents what stuff is, for sure.  
And because I know I am biased, I cross-referenced with the official GitHub documentation in German for many things. Which supported me in my stance.

I have to admit, I don't care enough about this to take another hour to read through this and try to find some suggestions on my side.  
You seem to be far more the target audience for this than me anyway.

(I have he/him pronouns in my bio BTW (: )

2024-10-04 10:47 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +SillyTavern bietet eine einheitliche Benutzeroberfläche für viele LLM-APIs (KoboldAI/CPP, Horde, NovelAI, Ooba, Tabby, OpenAI, OpenRouter, Claude, Mistral und mehr), ein mobilfreundliches Layout, ein
I cannot read the other translations, as I am not fluent in them. If it‘s translated in the UI for german, it makes sense to translate this here in the readme too, yeah.

2024-10-04 10:54 UTC, Wolfsblvt commented on .github/readme-de_de.md
> +### Vorgeschlagene Backends (nicht verbunden)
The original intent of that heading was not about connecting to the backends. It‘s affiliate.

Heißt wir listen hier mögliche Backends auf, aber wir arbeiten nicht mit denen Zusammen oder kriegen irgendwas dafür die hier zu listen. Wieder so eine schöne Stelle, wo es kein passendes deutsches Wort gibt. Aber „verbunden“ ist es nicht.

2024-10-04 10:57 UTC, X00LA commented
When I translate, I always assume that people who don't understand English will read it, so I always translate everything so that people can understand it.
I would like to apologize for the "she". I wasn't in your bio and was just guided by the avatar picture.

2024-10-04 11:12 UTC, Wolfsblvt commented
Yeah, that‘s where we likely just differ in opinion. I prefer to use terms that are known in that area/niche, and I‘d focus on re-using the same terms, translations (and also not-translated words) than bigger sites, industry leaders and Co.
That‘s why I referred to the German GitHub documentation when I suggested to not translate „Branch“, „Issue“, „Pull Request“ and similar things. They don‘t either, for people who actually read the documentation of how GitHub works.
But yeah, just a different take here.

There is more stuff. A few things I commented on that you neither replied to nor fixed.
Some are debatable or opinionated, sure. But Seraphina is our default character that gets shipped with ST. You translated characters/cards as „Charakterkarten“. Then „Standardfigur“ is not the correct translation here.

But I am here because Cohee asked me for feedback - likely because I am German and also know ST well enough. He should‘ve known I am pedantic too.
So yeah. 
Maybe I was the wrong guy to ask for this.

2024-10-04 11:49 UTC, X00LA commented
I've gone through everything now, so there shouldn't be any more problems.

2024-10-04 11:55 UTC, Wolfsblvt approved these changes

2024-10-04 13:07 UTC, Cohee1207 approved these changes

2024-10-04 13:07 UTC, merged