Send commands return value
SillyTavern/SillyTavern pull request #2922
Opened 2024-09-30 16:47 UTC by Wolfsblvt

### Changes
- Most send commands return the message being send now
  - `/sendas`
  - `/send`
  - `/sys`
  - `/comment`
  - `/ask` did already work this way
  - Can't be changed: `/trigger`, because by default it does not await the message generation
- Refactored checks on `/sendas` at the beginning, as they were very redundant
- Updated `/ask` toasts to warnings, being more consistent with the other commands.
  Errors should be reserved for something unexpectedly being wrong or actually failing. Missing or falsely formatted args can just be a warning.
- Function `sendMessageAsUser` now has a return value of the message object itself. Does not break existing code.

## Checklist:

- [x] I have read the [Contributing guidelines](https://www.youtube.com/watch?v=dQw4w9WgXcQ).

2024-09-30 17:57 UTC, Succubyss commented
I'm personally in favor. However, if this is refused, let the ability to have it return a value at least become a parameter like `emit=` or `pass=`

2024-09-30 19:02 UTC, Cohee1207 requested changes
This is a breaking change and I'm not a fan of it. This has limited usability (only ever usable if you have specific message-altering regex), but high muscle memory breakage potential. I'm ready to take a Luccy pill and suggest to enable this behavior with a named argument.

2024-09-30 20:02 UTC, Wolfsblvt commented
What would that one be named?

And should be update existing commands that are already returning to so this as well?

2024-09-30 20:59 UTC, Cohee1207 commented
> What would that one be named?

"return" is fine.

> And should be update existing commands that are already returning to so this as well?

Yes, but it's only /ask so far? + potential aliases and refactoring for /listinjects and /listvar

> output=, like the current listinjects might be an option too, but I have a feeling that might go against some commands where output does not make much sense.

Actually it's "format", not "output".  If you think this name sucks, let's add a couple aliases. And extract common function for doing the "return" thing.

2024-09-30 21:20 UTC, Wolfsblvt commented
> Actually it's "format", not "output". If you think this name sucks, let's add a couple aliases. And extract common function for doing the "return" thing.

Working on my fix/update. Gimme a bit. Though just wanted to reply, aliases for named aren't really well supported in the current implementation really. You'd have to build them yourself in the callback handler, which can be quite confusing. But it certainly is an option. Len said he does not want to have those though.

2024-09-30 22:46 UTC, Wolfsblvt commented
I am too tired to update the PR description or summarize the stuff in those commits. Read the commit messages and details you can expand :/
It done though.

2024-09-30 22:57 UTC, Cohee1207 commented on public/scripts/slash-commands/SlashCommandReturnHelper.js
> +                const htmlOrNotHtml = shouldHtml ? (new showdown.Converter()).makeHtml(stringValue) : escapeHtml(stringValue);
`/sendas return=toast-html name=Stelle <script>alert('pwned')</script>`

2024-09-30 23:01 UTC, Cohee1207 commented
`/listinjects` doesn't work when there are no injects in the chat. In staging it makes a toast that the chat has no injects.
<img width="546" alt="image" src="https://github.com/user-attachments/assets/26ed3b0b-27f0-49c0-8f8b-5fa1ca1beace">

2024-09-30 23:23 UTC, Wolfsblvt commented on public/scripts/slash-commands/SlashCommandReturnHelper.js
> +                const htmlOrNotHtml = shouldHtml ? (new showdown.Converter()).makeHtml(stringValue) : escapeHtml(stringValue);
Done. I had it in there before. Dunno where along the way it went poof.

2024-09-30 23:24 UTC, Wolfsblvt commented
> `/listinjects` doesn't work when there are no injects in the chat. In staging it makes a toast that the chat has no injects.

You think a toast is the best way if you want pipe or object as return? But it should not crash for sure.

2024-10-01 16:18 UTC, Cohee1207 commented
~~`format` in `classify-expressions` is not deprecated. It defines the actual piped value. I'm fixing that.~~

UPD: !jar

2024-10-01 16:25 UTC, Cohee1207 approved these changes
Tested. I didn't try every single return type on every single command, but those that I've tried work fine.

2024-10-01 16:25 UTC, merged