Improve mass-delete message interface
SillyTavern/SillyTavern pull request #2991
Opened 2024-10-15 19:04 UTC by InspectorCaracal

The current UX for deleting multiple chat messages at once only allows you to crop the tail of the chat log by selecting the message you click on and all other messages between it and the end of the chat history.

This PR replaces that behavior with the following behaviors:

- Individual messages can be marked or unmarked for deletion by clicking them.
- A range of messages can be marked or unmarked for deletion by clicking the first message, then holding Ctrl and clicking the second message.

## Checklist:

- [x] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

2024-10-15 20:38 UTC, Cohee1207 requested changes
1. For many this is going to break muscle memory since delete worked like this from the very beginning. I'm not going to ask to add a toggle, since no one likes toggles, but inverting this behavior would be nicer.
2. There are no visual clues about using keyboard for selecting ranges. Add a little hint above the "Delete" / "Cancel".
3. Ctrl+Click doesn't really work for Mac (it opens a context menu). And we already have several Shift+Clicks across the app, so I suggest to switch to Shift modifier.
4. Not really a major issue (at least for me), but mobile is gimped by having no way to replicate the Shift+Click behavior.

2024-10-15 20:43 UTC, Cohee1207 commented
The last review point could be mitigated by allowing to long-tap to select/deselect a single message

2024-10-15 21:57 UTC, InspectorCaracal commented
>     1. For many this is going to break muscle memory since delete worked like this from the very beginning. I'm not going to ask to add a toggle, since no one likes toggles, but inverting this behavior would be nicer.

I'm probably just being obtuse, but what does "inverting this behavior" mean?

>     3. Ctrl+Click doesn't really work for Mac (it opens a context menu). And we already have several Shift+Clicks across the app, so I suggest to switch to Shift modifier.

This might be a little tricky, but I'll give it a shot. I originally set it up with Shift but that winds up actually selecting text in the page, which was super annoying, so I'll have to figure out why and then figure out if changing the cause of that breaks anything else in the process.

2024-10-16 15:51 UTC, Cohee1207 commented
>  I originally set it up with Shift but that winds up actually selecting text in the page

Hmm, probably need to call `preventDefault` on the event or something along these lines

2025-05-01 20:58 UTC, closed without merging